### ISSUE TITLE
errors when running config

### ISSUE THREAD

**Issue by bruma59** [spacemanspiff2007/sml2mqtt#1]
What did I do wrong

(venv) root@DietPi:/opt/sml2mqtt/venv# sml2mqtt --config /opt/sml2mqtt
Traceback (most recent call last):
  File "/opt/sml2mqtt/venv/bin/sml2mqtt", line 6, in <module>
    from sml2mqtt.main import main
  File "/opt/sml2mqtt/venv/lib/python3.7/site-packages/sml2mqtt/main.py", line 1                                       3, in <module>
    from sml2mqtt.sml_device import Device
  File "/opt/sml2mqtt/venv/lib/python3.7/site-packages/sml2mqtt/sml_device.py",                                        line 7, in <module>
    from smllib import CrcError, SmlStreamReader
  File "/opt/sml2mqtt/venv/lib/python3.7/site-packages/smllib/__init__.py", line                                        3, in <module>
    from smllib.sml_frame import SmlFrame                # noqa: F401
  File "/opt/sml2mqtt/venv/lib/python3.7/site-packages/smllib/sml_frame.py", lin                                       e 107
    while (start := self.bytes.find(b'\x77\x07\x01', start + 1)) != -1:
                 ^
SyntaxError: invalid syntax

**Comment by spacemanspiff2007** [comment]
sml2mqtt requires python 3.8, you try to run it with python 3.7

**Comment by bruma59** [comment]
Thanks for the quick response. 
Dietpi-jessie auto upgraded to buster - python3.8 is not available yet for that debian
I'll try raspbian

**Comment by spacemanspiff2007** [comment]
I'll close this - feel free to reopen if you experience errors with python 3.8
