### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_value'

### ISSUE THREAD

**Issue by hello-world-dot-c** [spacemanspiff2007/sml2mqtt#50]
I have replaced the system that reads out my energy sensor, I am using the same sensor and configuration and have made sure that I have even used the same Pyton version - 3.9.2. Nevertheless, I am getting the error in the title. With the -a option I can see that it retrieves power and energy values from the received frame just fine before it throws the error. Below is what is installed in the venv and the output of the -a command:

```
(venv) user:/opt/sml2mqtt/venv$ python3 -m pip install --upgrade pip sml2mqtt
Requirement already satisfied: pip in ./lib/python3.9/site-packages (24.3.1)
Requirement already satisfied: sml2mqtt in ./lib/python3.9/site-packages (2.2)
Requirement already satisfied: asyncio-mqtt==0.16.1 in ./lib/python3.9/site-packages (from sml2mqtt) (0.16.1)
Requirement already satisfied: pyserial-asyncio==0.6 in ./lib/python3.9/site-packages (from sml2mqtt) (0.6)
Requirement already satisfied: easyconfig==0.2.8 in ./lib/python3.9/site-packages (from sml2mqtt) (0.2.8)
Requirement already satisfied: pydantic<2.0,>=1.10 in ./lib/python3.9/site-packages (from sml2mqtt) (1.10.19)
Requirement already satisfied: smllib==1.2 in ./lib/python3.9/site-packages (from sml2mqtt) (1.2)
Requirement already satisfied: paho-mqtt>=1.6.0 in ./lib/python3.9/site-packages (from asyncio-mqtt==0.16.1->sml2mqtt) (2.1.0)
Requirement already satisfied: typing-extensions>=4.4.0 in ./lib/python3.9/site-packages (from asyncio-mqtt==0.16.1->sml2mqtt) (4.12.2)
Requirement already satisfied: ruamel.yaml<0.18,>=0.17 in ./lib/python3.9/site-packages (from easyconfig==0.2.8->sml2mqtt) (0.17.40)
Requirement already satisfied: pyserial in ./lib/python3.9/site-packages (from pyserial-asyncio==0.6->sml2mqtt) (3.5)
Requirement already satisfied: ruamel.yaml.clib>=0.2.7 in ./lib/python3.9/site-packages (from ruamel.yaml<0.18,>=0.17->easyconfig==0.2.8->sml2mqtt) (0.2.12)

(venv) user:/opt/sml2mqtt/venv$ sml2mqtt --config /opt/sml2mqtt/sml2mqtt.conf -a
[2024-11-27 21:07:04,325] [sml                    ] INFO     | Starting V2.2
[2024-11-27 21:07:04,439] [sml.ttyUSB0.status     ] INFO     | PORT_OPENED
[2024-11-27 21:07:05,121] [sml.ttyUSB0            ] INFO     |
[2024-11-27 21:07:05,121] [sml.ttyUSB0            ] INFO     | Received Frame
[2024-11-27 21:07:05,125] [sml.ttyUSB0            ] INFO     |  -> b'7605017fa660620062007263010176010105007fe2200b0a0149534b000579235472620165003fef596201636c0e007605017fa661620062007263070177010b0a0149534b0005792354070100620affff72620165003fef59757707010060320101010101010449534b0177070100600100ff010101010b0a0149534b00057923540177070100010800ff65001c010401621e52ff6500778c730177070100020800ff0101621e52ff62000177070100100700ff0101621b520053021c0101016315ad007605017fa6626200620072630201710163ebd900'
[2024-11-27 21:07:05,125] [sml.ttyUSB0            ] INFO     |
[2024-11-27 21:07:05,126] [sml.ttyUSB0            ] INFO     | <SmlMessage>
[2024-11-27 21:07:05,126] [sml.ttyUSB0            ] INFO     |   transaction_id: 017fa660
[2024-11-27 21:07:05,126] [sml.ttyUSB0            ] INFO     |   group_no      : 0
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     |   abort_on_error: 0
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     |   message_body <SmlOpenResponse>
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     |     codepage   : None
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     |     client_id  : None
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     |     req_file_id: 007fe220
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     |     server_id  : 0a0149534b0005792354
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     |     ref_time   : 4190041
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     |     sml_version: 1
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     |   crc16         : 27662
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     | <SmlMessage>
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     |   transaction_id: 017fa661
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     |   group_no      : 0
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     |   abort_on_error: 0
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     |   message_body <SmlGetListResponse>
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     |     client_id       : None
[2024-11-27 21:07:05,127] [sml.ttyUSB0            ] INFO     |     server_id       : 0a0149534b0005792354
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |     list_name       : 0100620affff
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |     act_sensor_time : 4190041
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |     val_list:
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |       <SmlListEntry>
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         obis           : 010060320101 (1-0:96.50.1*1)
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         status         : None
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         val_time       : None
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         unit           : None
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         scaler         : None
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         value          : ISK
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         value_signature: None
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |       <SmlListEntry>
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         obis           : 0100600100ff (1-0:96.1.0*255)
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         status         : None
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         val_time       : None
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         unit           : None
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         scaler         : None
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         value          : 0a0149534b0005792354
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         value_signature: None
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |       <SmlListEntry>
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         obis           : 0100010800ff (1-0:1.8.0*255)
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         status         : 1835268
[2024-11-27 21:07:05,128] [sml.ttyUSB0            ] INFO     |         val_time       : None
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         unit           : 30
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         scaler         : -1
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         value          : 7834739
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         value_signature: None
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         -> 783473.9Wh (Zählerstand Total)
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |       <SmlListEntry>
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         obis           : 0100020800ff (1-0:2.8.0*255)
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         status         : None
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         val_time       : None
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         unit           : 30
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         scaler         : -1
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         value          : 0
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         value_signature: None
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         -> 0.0Wh (Wirkenergie Total)
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |       <SmlListEntry>
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         obis           : 0100100700ff (1-0:16.7.0*255)
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         status         : None
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         val_time       : None
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         unit           : 27
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         scaler         : 0
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         value          : 540
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         value_signature: None
[2024-11-27 21:07:05,129] [sml.ttyUSB0            ] INFO     |         -> 540W (aktuelle Wirkleistung)
[2024-11-27 21:07:05,130] [sml.ttyUSB0            ] INFO     |     list_signature  : None
[2024-11-27 21:07:05,130] [sml.ttyUSB0            ] INFO     |     act_gateway_time: None
[2024-11-27 21:07:05,130] [sml.ttyUSB0            ] INFO     |   crc16         : 5549
[2024-11-27 21:07:05,130] [sml.ttyUSB0            ] INFO     | <SmlMessage>
[2024-11-27 21:07:05,130] [sml.ttyUSB0            ] INFO     |   transaction_id: 017fa662
[2024-11-27 21:07:05,130] [sml.ttyUSB0            ] INFO     |   group_no      : 0
[2024-11-27 21:07:05,130] [sml.ttyUSB0            ] INFO     |   abort_on_error: 0
[2024-11-27 21:07:05,130] [sml.ttyUSB0            ] INFO     |   message_body <SmlCloseResponse>
[2024-11-27 21:07:05,130] [sml.ttyUSB0            ] INFO     |     global_signature: None
[2024-11-27 21:07:05,130] [sml.ttyUSB0            ] INFO     |   crc16         : 60377
[2024-11-27 21:07:05,130] [sml.ttyUSB0            ] INFO     |
[2024-11-27 21:07:05,130] [sml.ttyUSB0            ] INFO     | Creating value handler from config for 0100010800ff
[2024-11-27 21:07:05,130] [sml.ttyUSB0            ] INFO     | Creating value handler from config for 0100100700ff
[2024-11-27 21:07:05,130] [sml.ttyUSB0            ] WARNING  | Config for 0100240700ff found but 0100240700ff was not reported by the frame
[2024-11-27 21:07:05,130] [sml.ttyUSB0            ] INFO     | Creating value handler from config for 0100240700ff
[2024-11-27 21:07:05,131] [sml.ttyUSB0            ] WARNING  | Config for 0100380700ff found but 0100380700ff was not reported by the frame
[2024-11-27 21:07:05,131] [sml.ttyUSB0            ] INFO     | Creating value handler from config for 0100380700ff
[2024-11-27 21:07:05,131] [sml.ttyUSB0            ] WARNING  | Config for 01004c0700ff found but 01004c0700ff was not reported by the frame
[2024-11-27 21:07:05,131] [sml.ttyUSB0            ] INFO     | Creating value handler from config for 01004c0700ff
[2024-11-27 21:07:05,131] [sml.mqtt.pub           ] INFO     | sml2mqtt/house/energy: 783.474 (QOS: 0, retain: False)
[2024-11-27 21:07:05,131] [sml.mqtt.pub           ] INFO     | sml2mqtt/house/power: 540 (QOS: 0, retain: False)
[2024-11-27 21:07:05,131] [sml.ttyUSB0.status     ] INFO     | OK
[2024-11-27 21:07:05,131] [sml.mqtt.pub           ] INFO     | sml2mqtt/house/status: OK (QOS: 0, retain: False)
[2024-11-27 21:07:05,131] [sml.ttyUSB0            ] INFO     |
[2024-11-27 21:07:05,131] [sml.ttyUSB0            ] INFO     | sml2mqtt/house/energy (0100010800ff):
[2024-11-27 21:07:05,131] [sml.ttyUSB0            ] INFO     |   raw value: 783.4739
[2024-11-27 21:07:05,131] [sml.ttyUSB0            ] INFO     |   pub value: 783.474
[2024-11-27 21:07:05,131] [sml.ttyUSB0            ] INFO     |   transformations:
[2024-11-27 21:07:05,131] [sml.ttyUSB0            ] INFO     |     - <Round: 3>
[2024-11-27 21:07:05,131] [sml.ttyUSB0            ] INFO     |   filters:
[2024-11-27 21:07:05,131] [sml.ttyUSB0            ] INFO     |     - <AbsDiff: 10>
[2024-11-27 21:07:05,131] [sml.ttyUSB0            ] INFO     |     - <Every: 60>
[2024-11-27 21:07:05,131] [sml.ttyUSB0            ] INFO     |
[2024-11-27 21:07:05,132] [sml.ttyUSB0            ] INFO     | sml2mqtt/house/power (0100100700ff):
[2024-11-27 21:07:05,132] [sml.ttyUSB0            ] INFO     |   raw value: 540
[2024-11-27 21:07:05,132] [sml.ttyUSB0            ] INFO     |   pub value: 540
[2024-11-27 21:07:05,132] [sml.ttyUSB0            ] INFO     |   filters:
[2024-11-27 21:07:05,132] [sml.ttyUSB0            ] INFO     |     - <AbsDiff: 10>
[2024-11-27 21:07:05,132] [sml.ttyUSB0            ] INFO     |     - <PercDiff: 5>
[2024-11-27 21:07:05,132] [sml.ttyUSB0            ] INFO     |     - <Every: 20>
[2024-11-27 21:07:05,132] [sml.ttyUSB0            ] INFO     |
[2024-11-27 21:07:05,132] [sml.ttyUSB0            ] ERROR    | Received Frame
[2024-11-27 21:07:05,132] [sml.ttyUSB0            ] ERROR    |  -> b'7605017fa660620062007263010176010105007fe2200b0a0149534b000579235472620165003fef596201636c0e007605017fa661620062007263070177010b0a0149534b0005792354070100620affff72620165003fef59757707010060320101010101010449534b0177070100600100ff010101010b0a0149534b00057923540177070100010800ff65001c010401621e52ff6500778c730177070100020800ff0101621e52ff62000177070100100700ff0101621b520053021c0101016315ad007605017fa6626200620072630201710163ebd900'
[2024-11-27 21:07:05,133] [sml.ttyUSB0            ] ERROR    | Traceback (most recent call last):
[2024-11-27 21:07:05,133] [sml.ttyUSB0            ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.9/site-packages/sml2mqtt/device/sml_device.py", line 200, in serial_data_read
[2024-11-27 21:07:05,133] [sml.ttyUSB0            ] ERROR    |     self.process_frame(frame)
[2024-11-27 21:07:05,133] [sml.ttyUSB0            ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.9/site-packages/sml2mqtt/device/sml_device.py", line 289, in process_frame
[2024-11-27 21:07:05,133] [sml.ttyUSB0            ] ERROR    |     for line in value.describe().splitlines():
[2024-11-27 21:07:05,133] [sml.ttyUSB0            ] ERROR    |   File "/opt/sml2mqtt/venv/lib/python3.9/site-packages/sml2mqtt/sml_value/sml_value.py", line 61, in describe
[2024-11-27 21:07:05,133] [sml.ttyUSB0            ] ERROR    |     f'{once}raw value: {self.sml_value.get_value()}\n' \
[2024-11-27 21:07:05,133] [sml.ttyUSB0            ] ERROR    | AttributeError: 'NoneType' object has no attribute 'get_value'
[2024-11-27 21:07:05,133] [sml.ttyUSB0.status     ] INFO     | ERROR
[2024-11-27 21:07:05,133] [sml.mqtt.pub           ] INFO     | sml2mqtt/house/status: ERROR (QOS: 0, retain: False)
[2024-11-27 21:07:05,134] [sml.serial             ] INFO     | Port /dev/ttyUSB0 was closed
[2024-11-27 21:07:05,134] [sml.ttyUSB0.status     ] INFO     | PORT_CLOSED
[2024-11-27 21:07:05,135] [sml.mqtt.pub           ] INFO     | sml2mqtt/house/status: PORT_CLOSED (QOS: 0, retain: False)
Shutting down ...
[2024-11-27 21:07:05,142] [sml                    ] INFO     | Shutting down ...
```

**Comment by hello-world-dot-c** [comment]
Solved, I had additional value definitions in my config file that were triggering this error. After disabling those and also downgrading paho to 1.6.1 it is now running fine.

**Comment by spacemanspiff2007** [comment]
Just a heads up:
You are running a very old version of sml2mqtt. The current version requires python >= 3.10.

**Comment by hello-world-dot-c** [comment]
Thanks, I upgraded and converted the configuration to the new format and it now works fine under Python 3.12.
